### ISSUE TITLE
[BUG] I used nginx to redirect to HTTPS, However, it's keep reloading.

### ISSUE THREAD

**Issue by raychan907** [linuxserver/docker-duplicati#91]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

![image](https://github.com/user-attachments/assets/c5d6d7d6-acb2-414c-8bbe-79ef7bb24af3)

I am using docker duplicati:lastest version.
and Use nginx to redirect it to HTTPS

But something is not working.
May I confirm that how can I change http to https?

Thank you very much.

### Steps To Reproduce

![image](https://github.com/user-attachments/assets/404483a6-59f5-4cad-89b8-161e750430d1)

Nginx config 
    location ~ ^/duplicati(/.*)$ {
        proxy_read_timeout 300;
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_pass http://127.0.0.1:8200/$1$is_args$args;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Host $server_name;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
        proxy_redirect http://127.0.0.1:8200/ /duplicati/;
        proxy_cookie_path / /duplicati/;
        if ($scheme = https) {
            set $xforwardedssl "on";
        }
        proxy_set_header X-Forwarded-Ssl $xforwardedssl;

### Environment

```markdown
Ubuntu 24.04 LTS
ARM 64 - Raspberry PI5
```

### CPU architecture

arm64

### Docker creation

```bash
---
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    env_file:N
      - stack.env

    volumes:
      - /opt/duplicati/config:/config
      - /opt/duplicati/backups:/backups
      - /opt/duplicati/source:/source
    ports:
      - 8200:8200
    restart: unless-stopped
```

### Container logs

```bash
GET /notifications?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0eXAiOiJBY2Nlc3NUb2tlbiIsInNpZCI6IndlYnNlcnZlciIsImZhbSI6IjVCQTk3MUZDNzczQjJE
Q0EiLCJuYmYiOjE3MzU2MDA5MjYsImV4cCI6MTczNTYwMTgyNiwiaXNzIjoiaHR0cHM6Ly9kdXBsaWNhdGkiLCJhdWQiOiJodHRwczovL2R1cGxpY2F0aSJ9.p5SafxYbId-cw-pd3m1Y6ZiJ5LxcqBXjo7QoMtPTEek HTTP/1.1" 404 555 "-" "M
ozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36" "-"
```

**Comment by raychan907** [comment]
> Thanks for opening your first issue here! Be sure to follow the relevant issue templates, or risk having this issue marked as invalid.

What should I do?
Thanks

**Comment by j0nnymoe** [comment]
Can you access it normally via ip:port?

**Comment by raychan907** [comment]
> Can you access it normally via ip:port?

Yes. The http is working.
I can use it and backup to Cloud.
However, I tried to use Nginx to change it to HTTPS. It will keep reload the connection.

**Comment by j0nnymoe** [comment]
Looks like your issue is trying to do subfolder reverse proxy.

**Comment by raychan907** [comment]
> Looks like your issue is trying to do subfolder reverse proxy.

And I have any problem. When I login from https. it will redirect to /login.html. not /duplicati/login.html.

So That's why the my nginx config is so odd.

**Comment by j0nnymoe** [comment]
I can point you to our reverse proxy config we ship with swag: https://github.com/linuxserver/reverse-proxy-confs/blob/master/duplicati.subfolder.conf.sample but other than that, it's outside our support.

**Comment by raychan907** [comment]
I am not sure about wher is the files for
    include /config/nginx/proxy.conf;
    include /config/nginx/resolver.conf;

**Comment by j0nnymoe** [comment]
Their related to our reverse proxy, you can find the proxy.conf in our swag GitHub repo.

**Comment by raychan907** [comment]
> /config/nginx/proxy.conf

Thanks for your help. I have one more question. 
Is it possible to enable https from Duplicati?  if yes. I can just enable it and no need to redirect via Nignx.

**Comment by j0nnymoe** [comment]
You would need to check their documentation.

**Comment by clement-brodu** [comment]
Hello, 

see https://github.com/linuxserver/docker-duplicati/issues/89#issuecomment-2571682798

If it's like me, you should try to add these 2 WebSocket headers to your reverse proxy.

- `Upgrade` : `$http_upgrade`
- `Connection` : `$connection_upgrade`

**Comment by kenkendk** [comment]
> Is it possible to enable https from Duplicati? if yes. I can just enable it and no need to redirect via Nignx.

Yes, as [described in the documentation](https://docs.duplicati.com/duplicati-programs/server#ssl-tls-support), but there is no automatic LetsEncrypt, so you probably want to use Nginx.

> Looks like your issue is trying to do subfolder reverse proxy.

There is a problem in 2.1.0.2 where it tries to use a websocket on `/api/v1/notifications` regardless of the subfolder in the proxy. It has been fixed in source, and will be available "soon". It does not depend on HTTPS though 🤔

**Comment by raychan907** [comment]
> 你好
> 
> 參見 [#89 （評論）](https://github.com/linuxserver/docker-duplicati/issues/89#issuecomment-2571682798)
> 
> 如果和我一樣，你應該嘗試將這 2 個 WebSocket 標頭添加到你的反向代理中。
> 
> * `Upgrade`:`$http_upgrade`
> * `Connection`:`$connection_upgrade`

it is 

> Hello,
> 
> see [#89 (comment)](https://github.com/linuxserver/docker-duplicati/issues/89#issuecomment-2571682798)
> 
> If it's like me, you should try to add these 2 WebSocket headers to your reverse proxy.
> 
> * `Upgrade` : `$http_upgrade`
> * `Connection` : `$connection_upgrade`

Thanks for your sharing. But it is not work for me.

**Comment by raychan907** [comment]
> > Is it possible to enable https from Duplicati? if yes. I can just enable it and no need to redirect via Nignx.
> 
> Yes, as [described in the documentation](https://docs.duplicati.com/duplicati-programs/server#ssl-tls-support), but there is no automatic LetsEncrypt, so you probably want to use Nginx.
> 
> > Looks like your issue is trying to do subfolder reverse proxy.
> 
> There is a problem in 2.1.0.2 where it tries to use a websocket on `/api/v1/notifications` regardless of the subfolder in the proxy. It has been fixed in source, and will be available "soon". It does not depend on HTTPS though 🤔

Let me wait for the update. Thanks for your update :)

**Comment by Baukeo** [comment]
I also had the issue with constant reload of the webinterface behind nginx reverse proxy. I managed to resolve this with this config: 
 Add this to nginx.conf, see: https://futurestud.io/tutorials/nginx-how-to-fix-unknown-connection_upgrade-variable
 ```
map $http_upgrade $connection_upgrade {  
    default upgrade;
    ''      close;
}
```
And also add the 2 websocket headers as mentioned earlier in your siteconfig:

```
   proxy_set_header      Upgrade $http_upgrade;
   proxy_set_header      Connection $connection_upgrade;
```

**Comment by raychan907** [comment]
> proxy_set_header      Upgrade $http_upgrade;
>    proxy_set_header      Connection $connection_upgrade;

Thanks for your update.
However, it still does not work.
it still showing net::ERR_ABORTED 404 (Not Found)

**Comment by Baukeo** [comment]
Maybe you problem is this: 
`proxy_redirect http://127.0.0.1:8200/ /duplicati/;`
can you change that into:
`proxy_redirect http://127.0.0.1:8200/;`

**Comment by raychan907** [comment]
> 7

you mean  proxy_redirect / http://127.0.0.1:8200/; ?

**Comment by Baukeo** [comment]
Maybe just remove the whole redirect option.

**Comment by raychan907** [comment]
> Maybe just remove the whole redirect option.

It is showing 404. 
![image](https://github.com/user-attachments/assets/1cd15e30-218f-40ea-9f67-ac7b82191341)

**Comment by 1n5aN1aC** [comment]
I had this issues on two servers with different nginx setups.

One was easily solved by adding:

```
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
```

While the other one (a more complicated nginx setup) has not been solved yet.  Will update when solved.
